# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
- repo: local
  hooks:
    -   id: gh-upload-secrets
        name: gh-upload-secrets
        entry: ./script/gh-upload-secrets.sh
        language: script
        types: [python]
        pass_filenames: false
