# https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  commit-user-email:
    runs-on: ubuntu-latest
    name: commit-user-email
    env:
      COMMIT_USER_NAME: homebrew-releaser[bot]

    steps:
      - name: Set COMMIT_USER_EMAIL
        run: |
          echo "::set-output name=COMMIT_USER_EMAIL::${{ github.event.repository.owner.id }}+${COMMIT_USER_NAME}@users.noreply.github.com"
        id: commit-user-email

      - name: Get COMMIT_USER_EMAIL
        run: echo "${{ steps.commit-user-email.outputs.COMMIT_USER_EMAIL }}"
