on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  secret-user-id:
    runs-on: ubuntu-latest
    name: Secret USER_ID

    steps:
      - name: Secret USER_ID
        run: echo "${{ secrets.USER_ID }}"

