# https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  step-output:
    runs-on: ubuntu-latest
    name: step-output
    steps:
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: selected-color
      - name: Get color
        run: echo "The selected color is ${{ steps.selected-color.outputs.SELECTED_COLOR }}"
