# https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  step-output-and-env:
    runs-on: ubuntu-latest
    name: step-output-and-env
    steps:
      - name: Set COMMIT_USER_ID
        run: echo '::set-output name=COMMIT_USER_ID::${{ github.event.repository.owner.id }}'
        id: commit-user-id
      - name: Get COMMIT_USER_ID
        run: echo "The selected color is ${{ steps.commit-user-id.outputs.COMMIT_USER_ID }}"
