on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  user-id-github-script:
    runs-on: ubuntu-latest
    name: user-id-github-script
    steps:
      - name: Set COMMIT_USER_ID - GitHub Java Script API
        uses: actions/github-script@v4
        id: commit_user_id
        with:
          script: |
            return github.users.getByUsername({
              username: 'j5pu',
            })
      - name: Set ID
        run: echo "${{ steps.commit_user_id.outputs.result["status"] }}"
