on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  user-id-github-script:
    runs-on: ubuntu-latest
    name: user-id-github-script
    steps:
      - name: Set COMMIT_USER_ID - GitHub Java Script API
        uses: actions/github-script@v4
        id: commit_user_id
        with:
#          result-encoding: string
          script: |
            const rv = await github.users.getByUsername({
              username: 'j5pu',
            })
            console.log(rv.data.id)
            return rv.data.id
      - name: Set ID
        run: echo "${{ steps.commit_user_id.outputs.result }}"

      - name: Set ID
        run: echo "${{ toJSON(steps.commit_user_id.outputs.result) }}"
