on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  user-id-github-script:
    runs-on: ubuntu-latest
    name: user-id-github-script
    steps:
      - name: Set COMMIT_USER_ID - GitHub Java Script API
        uses: actions/github-script@v4
        id: commit_user_id
        with:
          script: |
            const rv = await github.users.getByUsername({
              username: 'j5pu',
            })
            console.log(rv.data.id)
            return rv.data.id

      - name: Get COMMIT_USER_ID
        run: echo "${{ steps.commit_user_id.outputs.result }}"

      - name: Set COMMIT_USER_ID - GitHub Java Script API - Simple
        uses: actions/github-script@v4
        id: commit_user_id_simple
        with:
          script: |
            return await github.users.getByUsername({
              username: 'j5pu',
            })

      - name: Get COMMIT_USER_ID - Simple
        run: echo "${{ steps.commit_user_id_simple.outputs.result }}"

