on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  user-id-curl-jq:
    runs-on: ubuntu-latest
    name: user-id-curl-q

    steps:
      - name: Set COMMIT_USER_ID - Curl API
        id: commit_user_id
        run: |
          COMMIT_USER_ID="$( curl -s --request GET \
            --url "${GITHUB_API_URL}/users/${{ github.repository_owner }}" \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' | jq '.id' )"
          echo "::set-output name=COMMIT_USER_ID::${COMMIT_USER_ID}"
      - name: Get COMMIT_USER_ID
        run: echo "${{ steps.commit_user_id.outputs.COMMIT_USER_ID }}"
