on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  var-env:
    runs-on: ubuntu-latest
    name: var-env

    env:
      COMMIT_USER_NAME: homebrew-releaser[bot]

    steps:
      - name: Get Commit User ID
        id: commit-user-id
        run: echo "${{ github.event.repository.owner.id }}"

      - name: Echo Commit User ID
        run: echo "${{ steps.jobs.outputs }}"

      - name: Create env vars
        env:
          COMMIT_USER_ID: ${{ github.event.repository.owner.id }}
#          COMMIT_USER_EMAIL: ${{ COMMIT_USER_ID }+${{ COMMIT_USER_NAME }}@users.noreply.github.com
          OWNER: ${{ toJSON(github.event.repository.owner) }}
          URL_USER_API: ${{ env.GITHUB_API_URL }}/users/${{ github.repository_owner }}
        run: |
          echo "COMMIT_USER_ID=$COMMIT_USER_ID"
          echo "COMMIT_USER_EMAIL=$COMMIT_USER_EMAIL"
          echo "COMMIT_USER_NAME=$COMMIT_USER_NAME"
          echo "OWNER=$OWNER"
          echo "URL_USER_API=$URL_USER_API"
      - name: Dump Job context
        env:
          ENV: ${{ toJSON(job) }}
        run: echo "$job"
      - name: Dump Env context
        env:
          ENV: ${{ toJSON(env) }}
        run: echo "$ENV"
