on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  var-env:
    runs-on: ubuntu-latest
    name: var-env

    env:
      URL_USER_API: ${{ GITHUB_API_URL }}/users/${{ github.repository_owner }}
#      USER: homebrew-releaser[bot]
#      ID: ${{ toJSON(github).event.repository.owner.id }}
#      EMAIL: ${{ ID }${{ USER }}@users.noreply.github.com

    steps:
      - run: echo "ID=$ID"  # env in run in UNIX format $ID
      - run: echo "USER=$USER"
      - run: echo "EMAIL='${EMAIL}'"
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
      - run: echo "${{ env }}"
