on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  var-env:
    runs-on: ubuntu-latest
    name: var-env

    env:
      USER: homebrew-releaser[bot]

    steps:
      - name: Create env vars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          URL_USER_API: ${{ env.GITHUB_API_URL }}
#          URL_USER_API: ${{ GITHUB_API_URL }}/users/${{ github.repository_owner }}
#          ID: ${{ toJSON(github).event.repository.owner.id }}
#          EMAIL: ${{ ID }${{ USER }}@users.noreply.github.com
      - run: echo "URL_USER_API=$URL_USER_API"
      - run: echo "ID=$ID"  # env in run in UNIX format $ID
      - run: echo "USER=$USER"
      - run: echo "EMAIL='${EMAIL}'"
      - name: Dump Env context
        env:
          ENV: ${{ toJSON(env) }}
        run: echo "$ENV"
