on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  var-env:
    runs-on: ubuntu-latest
    name: var-env

    env:
      COMMIT_USER: homebrew-releaser[bot]

    steps:
      - name: Create env vars
        env:
          COMMIT_ID: ${{ toJSON(github) }}
#          COMMIT_ID: ${{ toJSON(github).event.repository.owner.id }}
#          COMMIT_EMAIL: ${{ COMMIT_ID }${{ COMMIT_USER }}@users.noreply.github.com
#          URL_USER_API: ${{ GITHUB_API_URL }}/users/${{ github.repository_owner }}
        run: |
          echo "COMMIT_EMAIL=$COMMIT_EMAIL"
          echo "COMMIT_ID=$COMMIT_ID"
          echo "COMMIT_USER=$COMMIT_USER"
          echo "URL_USER_API=$URL_USER_API"
      - name: Dump Env context
        env:
          ENV: ${{ toJSON(env) }}
        run: echo "$ENV"
